### ISSUE TITLE
0.12 version available?

### ISSUE THREAD

**Issue by DaveGit** [jberkel/android-plugin#134]
Hi, I like to upgrade to 0.12, but the sbt android plugin is still 0.11.2 and thus not compatible.

Is there a 0.12 available?

I now use

libraryDependencies += 
  Defaults.sbtPluginExtra( 
    "org.scala-sbt" % "sbt-android-plugin" % "0.6.1", 
    "0.11.2", 
    "2.9.1" 
  ) 

inside 0.12.0 so I get

java.lang.NoSuchMethodError: sbt.SettingKey$.apply(Ljava/lang/String;Ljava/lang/
String;Lscala/reflect/Manifest;)Lsbt/SettingKey;
        at AndroidKeys$.<init>(AndroidKeys.scala:13)
        at AndroidKeys$.<clinit>(AndroidKeys.scala)
        at General$.<init>(build.scala:11)
        at General$.<clinit>(build.scala)

**Comment by jberkel** [comment]
0.6.2 works with sbt 0.12.x

**Comment by DaveGit** [comment]
Thanks, it works
